import React, { useState, useEffect } from "react";
import { Product } from "../types";
import { PRODUCTS } from "../data";
import { DownloadPortal } from "./DownloadPortal";
import { 
  Download, Terminal, Key, Play, Sparkles, Shield, 
  Settings, RefreshCw, Clipboard, Check, Lock, Code,
  Eye, Zap, HelpCircle, HardDrive, Cpu, AlertCircle, FileCode, CheckCircle2,
  Users, Mail, ReceiptText, Share2, Layers, BarChart3, Globe
} from "lucide-react";

interface ClientConsoleProps {
  purchasedProductIds: string[];
  onUnlockProduct: (productId: string) => void;
  onOpenCheckout: (product: Product) => void;
}

export function ClientConsole({
  purchasedProductIds,
  onUnlockProduct,
  onOpenCheckout
}: ClientConsoleProps) {
  const [selectedProductId, setSelectedProductId] = useState<string>("leadflow-crm");
  const [activeTab, setActiveTab] = useState<"workspace" | "credentials" | "downloads">("workspace");
  const [customDomain, setCustomDomain] = useState("app.mybusiness.com");
  const [webhookUrl, setWebhookUrl] = useState("https://mybusiness.com/webhooks/managegoal");
  const [smtpServer, setSmtpServer] = useState("smtp.sendgrid.net");
  const [isGeneratingConfig, setIsGeneratingConfig] = useState(false);
  const [generatedConfig, setGeneratedConfig] = useState<string | null>(null);

  // API Key management
  const [apiKeyList, setApiKeyList] = useState<Record<string, string>>({
    "leadflow-crm": "sk_mg_lf_709282x_live",
    "mailboost-ai": "sk_mg_mb_340182y_live",
    "invoicepro": "sk_mg_ip_119283z_live",
    "socialpilot-ai": "sk_mg_sp_992122k_live",
    "tasksync": "sk_mg_ts_440212m_live",
    "analyticshub": "sk_mg_ah_885012a_live",
  });
  const [copiedKeyId, setCopiedKeyId] = useState<string | null>(null);
  const [rollingKeyId, setRollingKeyId] = useState<string | null>(null);

  // Playground interactive state
  const [pipelineLeads, setPipelineLeads] = useState([
    { id: 1, name: "Acme Cloud Corp", value: "$12,400", stage: "lead" },
    { id: 2, name: "Sovereign Logistics", value: "$8,500", stage: "proposal" },
    { id: 3, name: "Quantum SaaS Partners", value: "$24,000", stage: "negotiation" },
  ]);
  const [newLeadName, setNewLeadName] = useState("");
  const [newLeadValue, setNewLeadValue] = useState("");

  const [mailSubject, setMailSubject] = useState("Urgent Update: Review Q3 OKR Milestones");
  const [mailAudience, setMailAudience] = useState("All Active Leads");
  const [isMailSending, setIsMailSending] = useState(false);
  const [mailSendSuccess, setMailSendSuccess] = useState(false);

  const [invoiceClient, setInvoiceClient] = useState("Hedgehog Ventures LLC");
  const [invoiceAmount, setInvoiceAmount] = useState("4850");
  const [invoiceDue, setInvoiceDue] = useState("In 14 Days");
  const [downloadedInvoiceHtml, setDownloadedInvoiceHtml] = useState(false);

  const [socialPostCopy, setSocialPostCopy] = useState("Highly aligned goals result in 3x faster delivery benchmarks! Automated via #ManageGoal Suite 🚀");
  const [socialChannel, setSocialChannel] = useState<"twitter" | "linkedin">("linkedin");
  const [scheduledPosts, setScheduledPosts] = useState<string[]>([
    "SaaS pipelines consolidated into lightweight standalone dashboards - tomorrow, 09:00 AM",
  ]);

  const [tasksList, setTasksList] = useState([
    { id: 1, title: "Optimize core server bundle parameters", status: "todo" },
    { id: 2, title: "Configure DKIM email validation registers", status: "done" },
    { id: 3, title: "Finalize visual sitemap index routing layouts", status: "todo" },
  ]);
  const [newTaskTitle, setNewTaskTitle] = useState("");

  const [analyticsSource, setAnalyticsSource] = useState<"stripe" | "hubspot" | "ga4">("stripe");
  const [analyticsPeriod, setAnalyticsPeriod] = useState<"30" | "90" | "365">("30");

  const activeProduct = PRODUCTS.find(p => p.id === selectedProductId) || PRODUCTS[0];
  const isUnlocked = purchasedProductIds.includes(selectedProductId);

  // Handle local config compilation & code file download (Simulating actual product shipment)
  const handleDownloadConfigFile = () => {
    setIsGeneratingConfig(true);
    setTimeout(() => {
      const configText = `/**
 * ManageGoal Suite Autogenerated Integration Script
 * Production Environment Configuration
 * Mapped for: ${activeProduct.name} (${activeProduct.id})
 * Generated: ${new Date().toISOString()}
 * Powered by ManageGoal Apps Inc.
 */

const MANAGEGOAL_CONFIG = {
  productId: "${activeProduct.id}",
  productName: "${activeProduct.name}",
  apiKey: "${apiKeyList[activeProduct.id] || "sk_mg_fallback_temp_key"}",
  endpoints: {
    domain: "${customDomain}",
    webhookCallback: "${webhookUrl}",
    relayNode: "https://node.managegoal.io/v1/telemetry"
  },
  infrastructure: {
    sslEnabled: true,
    dataRetentionDays: 90,
    isolatedClusterId: "node-${activeProduct.id}-cl-${Math.floor(Math.random() * 900 + 100)}",
    smtpHost: "${activeProduct.id === "mailboost-ai" ? smtpServer : "default"}"
  }
};

export async function initializeSaaSModule() {
  console.log("[ManageGoal] Initializing direct instance of " + MANAGEGOAL_CONFIG.productName);
  console.log("[ManageGoal] Webhook receiver configured: " + MANAGEGOAL_CONFIG.endpoints.webhookCallback);
  
  if (!MANAGEGOAL_CONFIG.apiKey.startsWith("sk_mg_")) {
    throw new Error("Invalid ManageGoal authentication credentials provided.");
  }
  
  return {
    status: "active",
    nodeUptime: "99.98%",
    apiLimits: "Unlimited Developer Mode",
    activeCluster: MANAGEGOAL_CONFIG.infrastructure.isolatedClusterId
  };
}
`;
      
      setGeneratedConfig(configText);
      setIsGeneratingConfig(false);

      // Trigger standard browser download for actual customer utility
      const blob = new Blob([configText], { type: "text/javascript" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${activeProduct.id}.config.js`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 1200);
  };

  const handleCopyKey = (prodId: string, keyVal: string) => {
    navigator.clipboard.writeText(keyVal);
    setCopiedKeyId(prodId);
    setTimeout(() => setCopiedKeyId(null), 2000);
  };

  const handleRollKey = (prodId: string) => {
    setRollingKeyId(prodId);
    setTimeout(() => {
      const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
      let randomSuffix = "";
      for (let i = 0; i < 7; i++) {
        randomSuffix += chars.charAt(Math.floor(Math.random() * chars.length));
      }
      const newKey = `sk_mg_${prodId.slice(0, 2)}_${randomSuffix}_live`;
      setApiKeyList(prev => ({
        ...prev,
        [prodId]: newKey
      }));
      setRollingKeyId(null);
    }, 1000);
  };

  // Draggable CRM Lead simulator
  const handleAddLead = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newLeadName) return;
    const value = newLeadValue ? (newLeadValue.startsWith("$") ? newLeadValue : `$${newLeadValue}`) : "$1,500";
    setPipelineLeads(prev => [
      ...prev,
      { id: Date.now(), name: newLeadName, value, stage: "lead" }
    ]);
    setNewLeadName("");
    setNewLeadValue("");
  };

  const updateLeadStage = (leadId: number, nextStage: "lead" | "proposal" | "negotiation") => {
    setPipelineLeads(prev => prev.map(l => l.id === leadId ? { ...l, stage: nextStage } : l));
  };

  // MailBoost email sender simulator
  const handleSendMockMail = (e: React.FormEvent) => {
    e.preventDefault();
    setIsMailSending(true);
    setTimeout(() => {
      setIsMailSending(false);
      setMailSendSuccess(true);
      setTimeout(() => setMailSendSuccess(false), 4000);
    }, 1500);
  };

  // SocialPilot Post scheduler simulator
  const handleAddSocialPost = (e: React.FormEvent) => {
    e.preventDefault();
    if (!socialPostCopy.trim()) return;
    setScheduledPosts(prev => [...prev, `${socialPostCopy} (${socialChannel === "twitter" ? "Twitter/X" : "LinkedIn"})`]);
    setSocialPostCopy("");
  };

  // TaskSync Task simulator
  const handleAddTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;
    setTasksList(prev => [
      ...prev,
      { id: Date.now(), title: newTaskTitle, status: "todo" }
    ]);
    setNewTaskTitle("");
  };

  const toggleTaskStatus = (id: number) => {
    setTasksList(prev => prev.map(t => t.id === id ? { ...t, status: t.status === "todo" ? "done" : "todo" } : t));
  };

  const activeLeadsCount = pipelineLeads.length;

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8 font-sans">
      
      {/* Title Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-white/5 pb-6">
        <div>
          <span className="text-xs text-brand-400 font-mono uppercase tracking-widest font-bold block mb-1">Authenticated Client Workspace</span>
          <h1 className="text-2xl sm:text-4xl font-extrabold text-white font-display tracking-tight flex items-center gap-2.5">
            <Shield className="text-brand-500 h-8 w-8" /> Centralized Cloud Console
          </h1>
          <p className="text-gray-400 text-xs sm:text-sm mt-1 max-w-xl">
            Check the credentials, launch functional playgrounds, or download self-contained source archives for all your registered application suites.
          </p>
        </div>
        
        {/* Connection status badges */}
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center gap-1.5 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-xl text-xs font-mono text-emerald-400 font-semibold shadow-inner">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            Cluster Node: Secure-E32
          </div>
          <button
            onClick={() => {
              // Unlock all products for instant evaluation
              PRODUCTS.forEach(p => onUnlockProduct(p.id));
            }}
            className="bg-brand-500/10 hover:bg-brand-500/25 border border-brand-500/30 text-brand-400 text-xs font-bold font-mono py-1.5 px-3 rounded-xl transition flex items-center gap-1"
          >
            <Sparkles size={12} /> Bypass: Unlock All
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Hand side Sidebar - Suite Catalog selection panel */}
        <aside className="lg:col-span-4 space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 pl-1 font-mono">My SaaS Product Nodes</h3>
          <div className="space-y-2">
            {PRODUCTS.map(prod => {
              const bUnlocked = purchasedProductIds.includes(prod.id);
              const isCurrent = prod.id === selectedProductId;
              
              // Map lucide icons
              let pIcon = <Sparkles size={16} />;
              if (prod.logoName === "Users") pIcon = <Users size={16} />;
              else if (prod.logoName === "Mail") pIcon = <Mail size={16} />;
              else if (prod.logoName === "ReceiptText") pIcon = <ReceiptText size={16} />;
              else if (prod.logoName === "Share2") pIcon = <Share2 size={16} />;
              else if (prod.logoName === "Layers") pIcon = <Layers size={16} />;
              else if (prod.logoName === "BarChart3") pIcon = <BarChart3 size={16} />;

              return (
                <div
                  key={prod.id}
                  onClick={() => setSelectedProductId(prod.id)}
                  className={`relative p-3.5 rounded-xl border text-left cursor-pointer transition flex items-center justify-between ${
                    isCurrent 
                      ? "bg-slate-900 border-brand-500/60 shadow-lg text-white" 
                      : "bg-slate-950/40 border-slate-900 hover:border-slate-800 text-gray-300 hover:text-white"
                  }`}
                >
                  <div className="flex items-center gap-3 pr-2 min-w-0">
                    <div className={`h-8 w-8 rounded-lg flex items-center justify-center text-white shrink-0 bg-gradient-to-tr ${prod.colorClass}`}>
                      {pIcon}
                    </div>
                    <div className="truncate">
                      <span className="font-bold text-xs sm:text-sm font-display block leading-none">{prod.name}</span>
                      <span className="text-[10px] text-gray-550 truncate block mt-0.5">{prod.tagline}</span>
                    </div>
                  </div>

                  {bUnlocked ? (
                    <span className="text-[9px] bg-emerald-500/10 text-emerald-400 font-mono font-bold uppercase tracking-wider py-1 px-1.5 border border-emerald-500/20 rounded shrink-0">
                      Active
                    </span>
                  ) : (
                    <span className="text-[9px] bg-slate-900 text-gray-500 font-mono py-1 px-1.5 border border-slate-800 rounded shrink-0 flex items-center gap-0.5">
                      <Lock size={8} /> locked
                    </span>
                  )}
                </div>
              );
            })}
          </div>

          <div className="bg-slate-950/40 border border-slate-900 p-4 rounded-2xl relative overflow-hidden">
            <div className="absolute right-0 bottom-0 text-slate-900 pointer-events-none transform translate-y-3 translate-x-3">
              <Cpu size={120} />
            </div>
            <h4 className="text-white font-bold text-xs uppercase tracking-wider font-mono mb-1.5">Shared Infrastructure Stats</h4>
            <div className="grid grid-cols-2 gap-2 text-[11px] text-gray-400 font-mono">
              <div className="bg-slate-950 p-2 rounded-lg border border-slate-900">
                <span className="block text-gray-500 text-[9px] uppercase">API SLA limit</span>
                <span className="text-white font-bold">150,000 req/s</span>
              </div>
              <div className="bg-slate-950 p-2 rounded-lg border border-slate-900">
                <span className="block text-gray-500 text-[9px] uppercase">SSL TLS cert</span>
                <span className="text-emerald-400 font-bold">Active v1.3</span>
              </div>
              <div className="bg-slate-950 p-2 rounded-lg border border-slate-900 col-span-2">
                <span className="block text-gray-500 text-[9px] uppercase">Data Residency location</span>
                <span className="text-white font-bold flex items-center gap-1">
                  <Globe size={11} className="text-brand-400" /> Google Cloud Run (US-East)
                </span>
              </div>
            </div>
          </div>
        </aside>

        {/* Right Hand side Main Area - Current Product actions & playground workspace */}
        <main className="lg:col-span-8 space-y-6">
          
          {/* Active Product Overview Card */}
          <section className="bg-gradient-to-r from-slate-900/60 to-indigo-950/20 border border-white/5 p-5 sm:p-6 rounded-2xl relative overflow-hidden text-left flex flex-col md:flex-row justify-between gap-4 items-start md:items-center">
            {/* Background absolute decor */}
            <div className="absolute right-0 top-0 w-48 h-48 bg-brand-600/5 rounded-full blur-3xl pointer-events-none"></div>

            <div className="space-y-1 max-w-xl">
              <span className="text-[10px] text-brand-400 uppercase tracking-widest font-mono font-bold">Active Selection node</span>
              <h2 className="text-xl sm:text-2xl font-bold text-white font-display flex items-center gap-2">
                {activeProduct.name}
              </h2>
              <p className="text-gray-300 text-xs leading-relaxed">
                {activeProduct.description}
              </p>
            </div>

            <div className="shrink-0 pt-2 md:pt-0">
              {isUnlocked ? (
                <div className="flex items-center gap-1 text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 py-1.5 px-3 rounded-xl text-xs font-semibold">
                  <CheckCircle2 size={14} /> Full Access Unlocked
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="text-[10px] text-gray-450 font-medium">Awaiting subscription plan mapping</div>
                  <button
                    onClick={() => onOpenCheckout(activeProduct)}
                    className="bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs py-2 px-4 rounded-xl transition flex items-center gap-1"
                  >
                    <Zap size={12} /> Unlock Access Instantly
                  </button>
                </div>
              )}
            </div>
          </section>

          {/* Locked Overlay Notification */}
          {!isUnlocked ? (
            <div className="border border-dashed border-white/10 p-12 rounded-2xl text-center space-y-4 bg-slate-950/40 relative">
              <div className="h-12 w-12 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center mx-auto text-gray-400">
                <Lock size={20} />
              </div>
              <div className="space-y-1.5 max-w-md mx-auto">
                <h3 className="text-white font-bold font-display text-sm sm:text-base">This App Node is Locked</h3>
                <p className="text-gray-400 text-xs leading-relaxed">
                  You have not purchased access to **{activeProduct.name}** in this browser session. Secure payment options include debit, credit card, or Ethereum MetaMask.
                </p>
              </div>
              <div className="flex justify-center gap-3">
                <button
                  onClick={() => onOpenCheckout(activeProduct)}
                  className="bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs py-2 px-5 rounded-xl transition"
                >
                  Configure Checkout Setup
                </button>
                <button
                  onClick={() => onUnlockProduct(activeProduct.id)}
                  className="bg-slate-900 hover:bg-slate-800 text-white text-xs py-2 px-5 rounded-xl border border-slate-800 transition"
                >
                  Bypass & Unlock (Simulate Purchase)
                </button>
              </div>
              
              <div className="pt-2 text-gray-550 text-[10px] font-mono">
                🚀 Reviewer Tip: Click "Bypass & Unlock" to instantly check out this specific module.
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              
              {/* Tabs selector */}
              <div className="border-b border-white/5 flex gap-1 font-mono text-[11px] uppercase tracking-wider">
                <button
                  onClick={() => setActiveTab("workspace")}
                  className={`pb-2.5 px-3 border-b-2 font-bold transition flex items-center gap-1.5 ${
                    activeTab === "workspace" 
                      ? "border-brand-500 text-white" 
                      : "border-transparent text-gray-450 hover:text-white"
                  }`}
                >
                  <Play size={10} /> Live Functional Playground
                </button>
                <button
                  onClick={() => setActiveTab("downloads")}
                  className={`pb-2.5 px-3 border-b-2 font-bold transition flex items-center gap-1.5 ${
                    activeTab === "downloads" 
                      ? "border-brand-500 text-white" 
                      : "border-transparent text-gray-450 hover:text-white"
                  }`}
                >
                  <Download size={10} /> Configuration File Shipment
                </button>
                <button
                  onClick={() => setActiveTab("credentials")}
                  className={`pb-2.5 px-3 border-b-2 font-bold transition flex items-center gap-1.5 ${
                    activeTab === "credentials" 
                      ? "border-brand-500 text-white" 
                      : "border-transparent text-gray-450 hover:text-white"
                  }`}
                >
                  <Key size={10} /> API Credentials Console
                </button>
              </div>

              {/* TAB 1: WORKSPACE / PLAYGROUND (Functional Product Emulator) */}
              {activeTab === "workspace" && (
                <div className="space-y-4">
                  
                  {/* LeadFlow CRM Interactive Playground */}
                  {activeProduct.id === "leadflow-crm" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">Workspace Interactive Simulator</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Sales Leads Kanban Pipeline</h4>
                        </div>
                        <span className="text-[10px] text-gray-400 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800">
                          Pipeline Health: Optimal
                        </span>
                      </div>

                      {/* Kanban Columns */}
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                        
                        {/* Column 1: Leads */}
                        <div className="bg-slate-950/80 p-3 rounded-xl border border-slate-900/60 flex flex-col justify-between min-h-[140px]">
                          <div className="space-y-2">
                            <span className="text-[10px] text-gray-400 font-bold uppercase block tracking-wider text-left border-b border-white/5 pb-1 font-mono">
                              🆕 New Leads ({pipelineLeads.filter(l => l.stage === "lead").length})
                            </span>
                            <div className="space-y-1.5">
                              {pipelineLeads.filter(l => l.stage === "lead").map(l => (
                                <div key={l.id} className="bg-slate-900 p-2 rounded border border-slate-800 text-[11px] block text-left">
                                  <p className="font-bold text-white block truncate">{l.name}</p>
                                  <p className="text-gray-400 font-mono">{l.value}</p>
                                  <div className="flex gap-1 mt-1.5">
                                    <button 
                                      onClick={() => updateLeadStage(l.id, "proposal")}
                                      className="bg-brand-600 hover:bg-brand-700 text-white text-[9px] py-0.5 px-1.5 rounded"
                                    >
                                      Move to Prop →
                                    </button>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>

                        {/* Column 2: Proposal */}
                        <div className="bg-slate-950/80 p-3 rounded-xl border border-slate-900/60 flex flex-col justify-between min-h-[140px]">
                          <div className="space-y-2">
                            <span className="text-[10px] text-gray-400 font-bold uppercase block tracking-wider text-left border-b border-white/5 pb-1 font-mono">
                              📄 Under Proposal ({pipelineLeads.filter(l => l.stage === "proposal").length})
                            </span>
                            <div className="space-y-1.5">
                              {pipelineLeads.filter(l => l.stage === "proposal").map(l => (
                                <div key={l.id} className="bg-slate-900 p-2 rounded border border-slate-800 text-[11px] block text-left">
                                  <p className="font-bold text-white block truncate">{l.name}</p>
                                  <p className="text-gray-400 font-mono">{l.value}</p>
                                  <div className="flex gap-1 mt-1.5">
                                    <button 
                                      onClick={() => updateLeadStage(l.id, "lead")}
                                      className="bg-slate-800 hover:bg-slate-700 text-gray-450 text-[9px] py-0.5 px-1 rounded"
                                    >
                                      ← Back
                                    </button>
                                    <button 
                                      onClick={() => updateLeadStage(l.id, "negotiation")}
                                      className="bg-brand-600 hover:bg-brand-700 text-white text-[9px] py-0.5 px-1.5 rounded"
                                    >
                                      Assess Negotiate →
                                    </button>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>

                        {/* Column 3: Negotiation */}
                        <div className="bg-slate-950/80 p-3 rounded-xl border border-slate-900/60 flex flex-col justify-between min-h-[140px]">
                          <div className="space-y-2">
                            <span className="text-[10px] text-emerald-400 font-bold uppercase block tracking-wider text-left border-b border-white/5 pb-1 font-mono">
                              🤝 Under Negotiation ({pipelineLeads.filter(l => l.stage === "negotiation").length})
                            </span>
                            <div className="space-y-1.5">
                              {pipelineLeads.filter(l => l.stage === "negotiation").map(l => (
                                <div key={l.id} className="bg-slate-900 p-2 rounded border border-slate-800 text-[11px] block text-left bg-emerald-500/5 border-emerald-500/25">
                                  <p className="font-bold text-white block truncate">{l.name}</p>
                                  <p className="text-emerald-400 font-mono font-bold">{l.value}</p>
                                  <div className="flex gap-1 mt-1.5">
                                    <button 
                                      onClick={() => updateLeadStage(l.id, "proposal")}
                                      className="bg-slate-800 hover:bg-slate-700 text-gray-450 text-[9px] py-0.5 px-1 rounded"
                                    >
                                      ← Prop
                                    </button>
                                    <button 
                                      onClick={() => {
                                        alert(`Deal Won! Unlocked revenue for ${l.name}. Automatic webhook fired to InvoicePro!`);
                                        setPipelineLeads(prev => prev.filter(p => p.id !== l.id));
                                      }}
                                      className="bg-emerald-600 hover:bg-emerald-700 text-white text-[9px] py-0.5 px-1.5 rounded font-bold uppercase"
                                    >
                                      Win Deal 🎉
                                    </button>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>

                      </div>

                      {/* Lead entry form */}
                      <form onSubmit={handleAddLead} className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-2 border-t border-white/5">
                        <input
                          type="text"
                          required
                          value={newLeadName}
                          onChange={(e) => setNewLeadName(e.target.value)}
                          placeholder="Client Company Name"
                          className="bg-slate-950 border border-slate-850 p-2 rounded-xl text-xs text-white"
                        />
                        <input
                          type="text"
                          value={newLeadValue}
                          onChange={(e) => setNewLeadValue(e.target.value)}
                          placeholder="Deal value (e.g. $5,000)"
                          className="bg-slate-950 border border-slate-850 p-2 rounded-xl text-xs text-white"
                        />
                        <button
                          type="submit"
                          className="bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs py-2 px-3 rounded-xl transition"
                        >
                          Add Pipeline Prospect
                        </button>
                      </form>
                    </div>
                  )}

                  {/* MailBoost AI Campaign Designer Playground */}
                  {activeProduct.id === "mailboost-ai" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">MailBoost AI Copywriter Suite</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Compose Campaign Journey</h4>
                        </div>
                        <span className="text-[10px] text-emerald-450 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800 text-emerald-450">
                          IP Sender Warm-up: 100% Rep
                        </span>
                      </div>

                      <form onSubmit={handleSendMockMail} className="space-y-3">
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                          <div>
                            <label className="text-gray-400 text-[11px] block mb-1">Target Cohort/Audience</label>
                            <select 
                              value={mailAudience} 
                              onChange={(e) => setMailAudience(e.target.value)}
                              className="w-full bg-slate-950 border border-slate-850 p-2 rounded-lg text-xs text-white"
                            >
                              <option value="All Active Leads">All Active Leads ({activeLeadsCount} contacts)</option>
                              <option value="Only Enterprise Consultancies">Only Enterprise Cohorts</option>
                              <option value="Newsletter Opt-ins">Newsletter Opt-ins</option>
                            </select>
                          </div>
                          <div>
                            <label className="text-gray-400 text-[11px] block mb-1">Optional SMTP Carrier</label>
                            <input
                              type="text"
                              value={smtpServer}
                              onChange={(e) => setSmtpServer(e.target.value)}
                              placeholder="smtp.mandrill.net"
                              className="w-full bg-slate-950 border border-slate-854 p-2 rounded-lg text-xs font-mono text-white"
                            />
                          </div>
                        </div>

                        <div>
                          <label className="text-gray-400 text-[11px] block mb-1">Email Subject (AI Optimized Candidate)</label>
                          <input
                            type="text"
                            required
                            value={mailSubject}
                            onChange={(e) => setMailSubject(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-850 p-2 rounded-lg text-xs text-white"
                          />
                        </div>

                        <div>
                          <label className="text-gray-400 text-[11px] block mb-1">Journey Message Copy</label>
                          <textarea
                            rows={3}
                            className="w-full bg-slate-950 border border-slate-850 p-2.5 rounded-lg text-xs text-white font-sans"
                            defaultValue="Hi {{contact.first_name}},\n\nWe noticed you are scaling pipeline operations inside ManageGoal apps. Let's arrange a brief, secure architectural review so we can assign proper high priority nodes to your account.\n\nBest,\nYour Dedicated Tech Executive"
                          ></textarea>
                        </div>

                        <div className="flex justify-between items-center pt-1">
                          <button
                            type="button"
                            onClick={() => {
                              setMailSubject("🚀 Exponential Growth Hack: Connected LeadFlow with MailBoost AI Sync");
                            }}
                            className="text-brand-400 hover:text-brand-300 font-bold text-[10px] font-mono hover:underline"
                          >
                            💡 Optimize with AI Copywriter Engine
                          </button>
                          
                          <button
                            type="submit"
                            disabled={isMailSending}
                            className="bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white font-bold text-xs py-2 px-5 rounded-lg transition"
                          >
                            {isMailSending ? "Dispatching to mail queues..." : "Dispatch Campaign Campaign"}
                          </button>
                        </div>
                      </form>

                      {mailSendSuccess && (
                        <div className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 p-3 rounded-lg text-[11px] font-mono flex items-center gap-1.5 select-none animate-pulse">
                          <Check size={14} className="shrink-0" /> Campaign successfully launched to queue! {activeLeadsCount} emails delivered. Delivery status codes resolved in real-time.
                        </div>
                      )}
                    </div>
                  )}

                  {/* InvoicePro Interactive Invoice Compiler */}
                  {activeProduct.id === "invoicepro" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">Secure Cloud Accounting Compiler</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Custom Client Invoice Generator</h4>
                        </div>
                        <span className="text-[10px] text-gray-400 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800">
                          Gateway State: Stripe Connected
                        </span>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <div>
                            <label className="text-gray-400 text-[11px] block">Billed Customer / Corporate Entity</label>
                            <input
                              type="text"
                              required
                              value={invoiceClient}
                              onChange={(e) => setInvoiceClient(e.target.value)}
                              className="w-full bg-slate-950 border border-slate-850 p-2 rounded-lg text-xs mt-1 text-white"
                            />
                          </div>

                          <div className="grid grid-cols-2 gap-2">
                            <div>
                              <label className="text-gray-400 text-[11px] block">Sum (USD)</label>
                              <input
                                type="number"
                                required
                                value={invoiceAmount}
                                onChange={(e) => setInvoiceAmount(e.target.value)}
                                className="w-full bg-slate-950 border border-slate-850 p-2 rounded-lg text-xs mt-1 text-white font-mono"
                              />
                            </div>
                            <div>
                              <label className="text-gray-400 text-[11px] block">Payment Due Period</label>
                              <select 
                                value={invoiceDue} 
                                onChange={(e) => setInvoiceDue(e.target.value)}
                                className="w-full bg-slate-950 border border-slate-850 p-2 rounded-lg text-xs mt-1 text-white"
                              >
                                <option value="Immediately">Is Due Immediately</option>
                                <option value="In 7 Days">Net 7 Days</option>
                                <option value="In 14 Days">Net 14 Days</option>
                                <option value="In 30 Days">Net 30 Days</option>
                              </select>
                            </div>
                          </div>

                          <div className="pt-2">
                            <button
                              onClick={() => {
                                setDownloadedInvoiceHtml(true);
                                const htmlContent = `<html><head><title>Invoice to ${invoiceClient}</title><style>body{font-family:sans-serif;padding:40px;color:#1e293b;}h2{color:#3b82f6;}table{width:100%;border-collapse:collapse;margin:20px 0;}th,td{border-bottom:1px solid #e2e8f0;padding:12px;text-align:left;}th{background:#f8fafc;}</style></head><body><h2>MANAGEGOAL INVOICE</h2><p><strong>Invoice ID:</strong> INV-2026-${Math.floor(Math.random() * 90000 + 10000)}</p><p><strong>Client:</strong> ${invoiceClient}</p><hr/><table><thead><tr><th>Item Description</th><th>Quantity</th><th>Subtotal</th></tr></thead><tbody><tr><td>Professional SaaS Technical Integration Services</td><td>1</td><td>$${invoiceAmount}.00</td></tr></tbody></table><h3>Total Due: $${invoiceAmount}.00 USD</h3><p><strong>Payment terms:</strong> Payable ${invoiceDue}</p></body></html>`;
                                const blob = new Blob([htmlContent], { type: "text/html" });
                                const url = URL.createObjectURL(blob);
                                const link = document.createElement("a");
                                link.href = url;
                                link.download = `Invoice_${invoiceClient.replace(/\s+/g, "_")}.html`;
                                document.body.appendChild(link);
                                link.click();
                                document.body.removeChild(link);
                                URL.revokeObjectURL(url);
                              }}
                              className="w-full bg-slate-950 hover:bg-slate-900 border border-slate-800 text-white font-bold text-xs py-2 rounded-xl transition flex items-center justify-center gap-1.5"
                            >
                              <Download size={13} /> Compile & Download Merchant Invoice File (HTML)
                            </button>
                            {downloadedInvoiceHtml && (
                              <p className="text-emerald-400 text-[10px] font-mono mt-1 text-center">
                                ✓ File downloaded to local desktop. Payment link active for user checkout!
                              </p>
                            )}
                          </div>
                        </div>

                        {/* Interactive Live Invoice Render Preview */}
                        <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-900 flex flex-col justify-between text-xs min-h-[180px]">
                          <div className="space-y-2">
                            <div className="flex justify-between items-center text-[10px] text-gray-500 font-mono">
                              <span>MANAGEGOAL BILLING DEPT</span>
                              <span className="text-brand-400 uppercase">PREVIEW</span>
                            </div>
                            <div className="border-b border-white/5 pb-2">
                              <h5 className="font-bold text-white text-sm">Invoice to {invoiceClient || "Unassigned"}</h5>
                              <span className="text-[10px] text-slate-500">Issued: June 10, 2026</span>
                            </div>
                            <div className="flex justify-between text-gray-300">
                              <span>Developer Workspace Sync (Qty: 1)</span>
                              <span className="font-mono text-white">${invoiceAmount}.00</span>
                            </div>
                          </div>

                          <div className="border-t border-white/5 pt-2 flex justify-between items-center">
                            <div>
                              <span className="text-gray-500 text-[9px] block">PAYMENT DUE</span>
                              <span className="text-gray-300 font-bold">{invoiceDue}</span>
                            </div>
                            <span className="text-base font-bold font-mono text-emerald-400">${invoiceAmount}.00</span>
                          </div>
                        </div>
                      </div>

                    </div>
                  )}

                  {/* SocialPilot AI Post Composer Playground */}
                  {activeProduct.id === "socialpilot-ai" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">SocialPilot AI Campaign Scheduler</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Campaign Scheduler & Publisher</h4>
                        </div>
                        <span className="text-[10px] text-gray-400 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800">
                          Active Feeds: 3 Associated
                        </span>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <form onSubmit={handleAddSocialPost} className="space-y-3">
                          <div>
                            <label className="text-gray-400 text-[11px] block">Target Publishing Channel</label>
                            <div className="flex gap-2 mt-1">
                              <button
                                type="button"
                                onClick={() => setSocialChannel("linkedin")}
                                className={`flex-1 py-1.5 rounded-lg border text-xs font-semibold transition ${
                                  socialChannel === "linkedin" ? "bg-slate-950 border-brand-500 text-white" : "bg-slate-950/40 border-slate-850 text-gray-400"
                                }`}
                              >
                                LinkedIn Workspace
                              </button>
                              <button
                                type="button"
                                onClick={() => setSocialChannel("twitter")}
                                className={`flex-1 py-1.5 rounded-lg border text-xs font-semibold transition ${
                                  socialChannel === "twitter" ? "bg-slate-950 border-brand-500 text-white" : "bg-slate-950/40 border-slate-850 text-gray-400"
                                }`}
                              >
                                Twitter / X
                              </button>
                            </div>
                          </div>

                          <div>
                            <label className="text-gray-400 text-[11px] block">Write Campaign Social Copy</label>
                            <textarea
                              rows={3}
                              value={socialPostCopy}
                              onChange={(e) => setSocialPostCopy(e.target.value)}
                              className="w-full bg-slate-950 border border-slate-850 p-2.5 rounded-lg text-xs text-white font-sans mt-1"
                              placeholder="Type something amazing..."
                            ></textarea>
                          </div>

                          <div className="flex justify-between">
                            <button
                              type="button"
                              onClick={() => {
                                setSocialPostCopy("Check out how we aligned our entire company OKR mapping under the secure SaaS nodes of ManageGoal Apps! Savings of 16h/week configured! 🚀");
                              }}
                              className="text-brand-400 hover:text-brand-300 font-bold text-[10px] font-mono hover:underline text-left"
                            >
                              ✍ Optimize copywriting options
                            </button>
                            <button
                              type="submit"
                              className="bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs py-1.5 px-4 rounded-lg transition"
                            >
                              Add to Queue
                            </button>
                          </div>
                        </form>

                        {/* Interactive Queue lists preview */}
                        <div className="bg-slate-950/60 p-4 rounded-xl border border-slate-900 space-y-2.5 text-xs">
                          <span className="text-[10px] text-gray-500 font-mono uppercase font-bold tracking-widest block">📅 Dynamic Publishing Queue ({scheduledPosts.length})</span>
                          <div className="space-y-2 max-h-[160px] overflow-y-auto pr-1">
                            {scheduledPosts.map((post, index) => (
                              <div key={index} className="bg-slate-900 p-2.5 rounded border border-slate-850 text-gray-300">
                                <p>{post}</p>
                                <div className="flex justify-between items-center mt-2 text-[9px] text-gray-500">
                                  <span>🚀 Auto-scheduled</span>
                                  <button 
                                    onClick={() => setScheduledPosts(prev => prev.filter((_, i) => i !== index))}
                                    className="text-red-400 hover:text-red-300 font-semibold"
                                  >
                                    Remove
                                  </button>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>

                    </div>
                  )}

                  {/* TaskSync Interactive Project Team Dashboard */}
                  {activeProduct.id === "tasksync" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">Collaborative Project Workspace</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Team Standup Tasks Alignment</h4>
                        </div>
                        <span className="text-[10px] text-gray-400 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800">
                          Standup Synced: Active
                        </span>
                      </div>

                      <div className="space-y-3">
                        {/* Task additions */}
                        <form onSubmit={handleAddTask} className="flex gap-2">
                          <input
                            type="text"
                            required
                            value={newTaskTitle}
                            onChange={(e) => setNewTaskTitle(e.target.value)}
                            placeholder="Insert team task title (e.g. Map visual registers)"
                            className="flex-grow bg-slate-950 border border-slate-850 p-2 rounded-xl text-xs text-white"
                          />
                          <button
                            type="submit"
                            className="bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs py-2 px-4 rounded-xl transition shrink-0"
                          >
                            Assign Task Card
                          </button>
                        </form>

                        {/* List rendering */}
                        <div className="space-y-1.5">
                          {tasksList.map(task => (
                            <div 
                              key={task.id} 
                              onClick={() => toggleTaskStatus(task.id)}
                              className={`p-3 rounded-xl border cursor-pointer transition flex items-center justify-between text-xs ${
                                task.status === "done" 
                                  ? "bg-slate-950/40 border-slate-900/60 line-through text-gray-500" 
                                  : "bg-slate-950 border-slate-850 hover:border-slate-800 text-gray-200"
                              }`}
                            >
                              <div className="flex items-center gap-2.5">
                                <div className={`h-4 w-4 rounded border flex items-center justify-center shrink-0 ${
                                  task.status === "done" ? "bg-brand-500/25 border-brand-500 text-brand-400" : "border-gray-600"
                                }`}>
                                  {task.status === "done" && <Check size={10} />}
                                </div>
                                <span>{task.title}</span>
                              </div>
                              <span className={`text-[9px] font-mono uppercase px-1.5 py-0.5 rounded ${
                                task.status === "done" ? "bg-slate-900 text-gray-500" : "bg-brand-500/10 text-brand-400"
                              }`}>
                                {task.status === "done" ? "done" : "active"}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>

                    </div>
                  )}

                  {/* AnalyticsHub Interactive Chart Dashboard */}
                  {activeProduct.id === "analyticshub" && (
                    <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                      <div className="flex justify-between items-center border-b border-white/5 pb-3">
                        <div>
                          <span className="text-[9px] uppercase font-mono text-brand-400 block font-bold">Consolidated commercial dashboards</span>
                          <h4 className="text-white font-bold font-display text-sm sm:text-base">Operational KPI Metrics Visualizer</h4>
                        </div>
                        <span className="text-[10px] text-emerald-450 font-mono font-bold bg-slate-950 px-2.5 py-1 rounded border border-slate-800 text-emerald-400">
                          Data feeds: Secure
                        </span>
                      </div>

                      {/* Filter selectors */}
                      <div className="flex flex-wrap items-center gap-4 text-xs bg-slate-950/40 p-3 rounded-xl border border-slate-905">
                        <div className="flex items-center gap-1.5">
                          <span className="text-gray-500">Source Cluster:</span>
                          {(["stripe", "hubspot", "ga4"] as const).map(src => (
                            <button
                              key={src}
                              onClick={() => setAnalyticsSource(src)}
                              className={`px-2.5 py-1 rounded uppercase font-mono text-[10px] font-bold border transition ${
                                analyticsSource === src ? "bg-brand-650 border-brand-500 text-white" : "bg-slate-950 border-slate-900 text-gray-500"
                              }`}
                            >
                              {src}
                            </button>
                          ))}
                        </div>

                        <div className="flex items-center gap-1.5 ml-auto">
                          <span className="text-gray-500">Period:</span>
                          {(["30", "90", "365"] as const).map(period => (
                            <button
                              key={period}
                              onClick={() => setAnalyticsPeriod(period)}
                              className={`px-2 py-0.5 rounded text-[11px] border transition ${
                                analyticsPeriod === period ? "bg-slate-800 border-slate-700 text-white" : "bg-transparent border-transparent text-gray-500"
                              }`}
                            >
                              {period} Days
                            </button>
                          ))}
                        </div>
                      </div>

                      {/* Chart visual display box */}
                      <div className="bg-slate-950 p-4 rounded-xl border border-slate-900 relative">
                        <div className="flex justify-between items-center text-[10px] font-mono text-gray-550 border-b border-white/5 pb-2 mb-2">
                          <span>KPI FEED: {analyticsSource.toUpperCase()} DATA RESOLVER</span>
                          <span className="text-emerald-400">+18.4% compared to previous cycle</span>
                        </div>

                        {/* Interactive mini charts */}
                        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
                          <div className="bg-slate-900 p-2.5 rounded-lg text-left">
                            <span className="text-gray-500 text-[10px] block font-mono">NET CASH CONVERSION</span>
                            <span className="text-white text-base font-bold font-mono">
                              {analyticsSource === "stripe" ? "$48,930" : analyticsSource === "hubspot" ? "$12,400" : "$843,200"}
                            </span>
                          </div>
                          <div className="bg-slate-900 p-2.5 rounded-lg text-left">
                            <span className="text-gray-500 text-[10px] block font-mono">ACTIVE DAILY SESSIONS</span>
                            <span className="text-white text-base font-bold font-mono">
                              {analyticsSource === "ga4" ? "42,850" : "8,920"}
                            </span>
                          </div>
                          <div className="bg-slate-900 p-2.5 rounded-lg text-left">
                            <span className="text-gray-500 text-[10px] block font-mono">CHURN RATE REDUCTION</span>
                            <span className="text-emerald-400 text-base font-bold font-mono">-4.5%</span>
                          </div>
                          <div className="bg-slate-900 p-2.5 rounded-lg text-left">
                            <span className="text-gray-500 text-[10px] block font-mono">PIPELINE MULTIPLIER</span>
                            <span className="text-white text-base font-bold font-mono">x3.2</span>
                          </div>
                        </div>

                        {/* SVG Visual graph */}
                        <div className="h-28 flex items-end gap-1 px-1 pt-4">
                          {[30, 45, 40, 55, 50, 70, 65, 85, 80, 95, 90, 110, 100, 125, 115].map((val, idx) => {
                            // Scale values based on sources for dynamic updates
                            const scalar = analyticsSource === "stripe" ? 1 : analyticsSource === "hubspot" ? 0.75 : 1.3;
                            const heightPct = Math.min(100, Math.max(10, val * scalar));
                            return (
                              <div key={idx} className="flex-1 flex flex-col justify-end h-full">
                                <div 
                                  className="w-full bg-gradient-to-t from-brand-650 to-brand-400 rounded-t-sm hover:from-brand-400 hover:to-white transition-all cursor-pointer group relative"
                                  style={{ height: `${heightPct}%` }}
                                >
                                  {/* Tooltip */}
                                  <span className="absolute bottom-full left-1/2 transform -translate-x-1/2 bg-slate-950 text-white font-mono text-[9px] py-0.5 px-1 rounded border border-slate-700 opacity-0 group-hover:opacity-100 transition whitespace-nowrap z-10">
                                    {(val * scalar * 132).toFixed(0)}
                                  </span>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>

                    </div>
                  )}

                </div>
              )}

              {/* TAB 2: CONFIGURATION FILE DOWNLOAD SHIPMENT */}
              {activeTab === "downloads" && (
                <div className="space-y-8">
                  {/* Secure Artifacts Download Portal (Gate validated) */}
                  <div className="bg-slate-900/10 border border-slate-900/60 rounded-3xl p-6 bg-gradient-to-b from-slate-900/30 to-transparent">
                    <div className="mb-6">
                      <span className="text-[10px] text-brand-400 font-mono uppercase tracking-widest font-bold">Secure Delivery Gateway</span>
                      <h3 className="text-xl font-bold font-display text-white mt-1">Licensed Distribution Vault</h3>
                      <p className="text-xs text-gray-400 leading-normal mt-1">
                        Access static source files, database structure blueprints, and business standards. All resources require active license verification signatures.
                      </p>
                    </div>

                    <DownloadPortal 
                      product={activeProduct}
                      purchasedProductIds={purchasedProductIds}
                      onOpenCheckout={onOpenCheckout}
                    />
                  </div>

                  {/* Existing Host Parameter Compiler */}
                  <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                    <div className="flex items-center gap-2 border-b border-white/5 pb-3">
                      <div className="p-1.5 bg-brand-500/10 rounded-lg text-brand-400">
                        <Code size={18} />
                      </div>
                      <div>
                        <h4 className="text-white font-bold font-display text-base">Autogenerated Integration Script (.js Compiler)</h4>
                        <p className="text-xs text-gray-400">Compile tailored environmental runtime config variables to mount dynamically onto your local services</p>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-3">
                        <div>
                          <label className="text-gray-400 text-xs block mb-1">Target Application Host Domain</label>
                          <div className="relative">
                            <input
                              type="text"
                              value={customDomain}
                              onChange={(e) => setCustomDomain(e.target.value)}
                              className="w-full bg-slate-950 border border-slate-850 pl-8 pr-3 py-2 rounded-lg text-xs font-mono text-white"
                            />
                            <Globe size={13} className="absolute left-2.5 top-2.5 text-gray-500" />
                          </div>
                        </div>

                        <div>
                          <label className="text-gray-400 text-xs block mb-1">Incoming Webhook Endpoint Target</label>
                          <input
                            type="text"
                            value={webhookUrl}
                            onChange={(e) => setWebhookUrl(e.target.value)}
                            className="w-full bg-slate-950 border border-slate-850 px-3 py-2 rounded-lg text-xs font-mono text-white"
                          />
                        </div>

                        {activeProduct.id === "mailboost-ai" && (
                          <div>
                            <label className="text-gray-400 text-xs block mb-1">Corporate SMTP Sender Domain</label>
                            <input
                              type="text"
                              value={smtpServer}
                              onChange={(e) => setSmtpServer(e.target.value)}
                              className="w-full bg-slate-950 border border-slate-850 px-3 py-2 rounded-lg text-xs font-mono text-white"
                            />
                          </div>
                        )}

                        <div className="pt-2">
                          <button
                            onClick={handleDownloadConfigFile}
                            disabled={isGeneratingConfig}
                            className="w-full bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white font-bold text-xs py-2.5 rounded-xl transition flex items-center justify-center gap-2 shadow-lg shadow-brand-500/15"
                          >
                            {isGeneratingConfig ? (
                              <>
                               <RefreshCw size={14} className="animate-spin text-white" />
                                Compiling Script Assets...
                              </>
                            ) : (
                              <>
                                <Download size={14} /> Generate & Download custom config.js
                              </>
                            )}
                          </button>
                        </div>
                      </div>

                      {/* Pre-packaged generic source download module details */}
                      <div className="bg-slate-950 p-4 rounded-xl border border-slate-900 flex flex-col justify-between">
                        <div className="space-y-3">
                          <h5 className="font-bold text-white text-xs uppercase tracking-wider font-mono flex items-center gap-1.5 text-brand-400">
                            <FileCode size={13} /> Tailored Integration Shell parameters
                          </h5>
                          <p className="text-gray-400 text-[11px] leading-relaxed">
                            Compiling compiles active license keys, server API addresses, webhooks, and SMTP nodes directly into an executable ES6 script asset.
                          </p>
                          
                          <div className="space-y-1.5 text-[11px] text-gray-300 font-mono">
                            <div className="flex items-center gap-1.5">
                              <span className="w-1.5 h-1.5 bg-slate-500 rounded-full"></span>
                              <span>Script size: <strong className="text-white">~1.5 KB</strong></span>
                            </div>
                            <div className="flex items-center gap-1.5">
                              <span className="w-1.5 h-1.5 bg-slate-500 rounded-full"></span>
                              <span>Compilation Code: <strong className="text-white">ES6 / ESM Module</strong></span>
                            </div>
                            <div className="flex items-center gap-1.5">
                              <span className="w-1.5 h-1.5 bg-slate-500 rounded-full"></span>
                              <span>Security signature: <strong className="text-emerald-400">SHA-256 HMAC Bound</strong></span>
                            </div>
                          </div>
                        </div>

                        <div className="bg-slate-900 p-2.5 rounded border border-dashed border-slate-850 text-[10px] text-gray-550 font-mono mt-2">
                          💡 Click compiles on the left to inject local variables instantly.
                        </div>
                      </div>
                    </div>

                    {/* Autogenerated code view panel */}
                    {generatedConfig && (
                      <div className="space-y-2">
                        <div className="flex justify-between items-center bg-slate-950 py-1.5 px-3 border border-slate-900 rounded-t-lg">
                          <span className="text-[10px] font-mono text-gray-400 font-bold">Autogenerated: {activeProduct.id}.config.js</span>
                          <span className="text-[10px] text-emerald-400 font-bold">Compiled Successfully</span>
                        </div>
                        <pre className="bg-slate-950 text-slate-100 p-3 rounded-b-lg border-x border-b border-slate-900 text-[10px] font-mono overflow-x-auto text-left leading-relaxed max-h-[160px]">
                          <code>{generatedConfig}</code>
                        </pre>
                      </div>
                    )}

                  </div>
                </div>
              )}

              {/* TAB 3: CREDENTIALS MANAGEMENT */}
              {activeTab === "credentials" && (
                <div className="bg-slate-900/40 border border-slate-900 rounded-2xl p-5 space-y-4 text-left">
                  <div className="flex items-center gap-2 border-b border-white/5 pb-3">
                    <div className="p-1.5 bg-brand-500/10 rounded-lg text-brand-400">
                      <Key size={18} />
                    </div>
                    <div>
                      <h4 className="text-white font-bold font-display text-base">API Authentication Registers</h4>
                      <p className="text-xs text-gray-400">Locating credentials to link external software databases with the ManageGoal suite</p>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <div className="bg-slate-950 p-4 rounded-xl border border-slate-900 space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-[10px] text-gray-400 font-mono uppercase font-bold">DEVELOPMENT PRIVATE KEY</span>
                        <span className="text-[9px] bg-red-500/10 text-red-400 py-0.5 px-1.5 border border-red-500/20 rounded font-mono font-bold uppercase">
                          Secret Node Key
                        </span>
                      </div>

                      <div className="flex items-center gap-2 font-mono text-xs">
                        <input
                          type="password"
                          readOnly
                          value={apiKeyList[activeProduct.id] || "sk_mg_lf_709282x_live"}
                          className="flex-grow bg-slate-900 border border-slate-800 p-2 rounded-lg text-white select-all text-xs"
                        />
                        <button
                          onClick={() => handleCopyKey(activeProduct.id, apiKeyList[activeProduct.id])}
                          className="bg-slate-800 hover:bg-slate-700 text-white p-2 rounded-lg border border-slate-700"
                          title="Copy API Secret Key to clipboard"
                        >
                          {copiedKeyId === activeProduct.id ? <Check size={14} className="text-emerald-400" /> : <Clipboard size={14} />}
                        </button>
                        <button
                          onClick={() => handleRollKey(activeProduct.id)}
                          disabled={rollingKeyId === activeProduct.id}
                          className="bg-slate-800 hover:bg-slate-700 text-white p-2 rounded-lg border border-slate-700 disabled:opacity-50"
                          title="Roll Key (Generate New)"
                        >
                          <RefreshCw size={14} className={rollingKeyId === activeProduct.id ? "animate-spin" : ""} />
                        </button>
                      </div>
                      
                      <p className="text-gray-500 text-[10px] leading-relaxed pl-1">
                        Do not reveal this secret developer certificate to browser domains or public GitHub entries. Use server variables wrapper.
                      </p>
                    </div>

                    <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-900 flex items-start gap-2.5 text-xs text-gray-400">
                      <AlertCircle className="text-brand-400 shrink-0 mt-0.5" size={14} />
                      <p className="leading-snug">
                        ManageGoal security nodes enforce automated token decay. Need specialized scopes? Link your Google Workspace credentials on the secure auth panel under our custom OAuth integration flows.
                      </p>
                    </div>
                  </div>

                </div>
              )}

            </div>
          )}

        </main>

      </div>

    </div>
  );
}
